FROM public.ecr.aws/lambda/nodejs:24-x86_64

RUN dnf install -y fontconfig

# Copy function code
COPY dist ${LAMBDA_TASK_ROOT}
COPY package-lock.json package.json ${LAMBDA_TASK_ROOT}

RUN npm i --include prod

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambdaMasto.handler" ]
