FROM public.ecr.aws/lambda/nodejs:22-x86_64

RUN dnf install -y fontconfig

# Copy function code
COPY dist/bluesky/package-lock.json dist/bluesky/package.json ${LAMBDA_TASK_ROOT}/
COPY dist/bluesky/lambda.js ${LAMBDA_TASK_ROOT}/lambda.js

RUN npm i --include prod

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda.handler" ]
