FROM public.ecr.aws/lambda/nodejs:22

RUN dnf install -y fontconfig

# Copy function code
COPY dist/bluesky/data ${LAMBDA_TASK_ROOT}/data
COPY dist/bluesky/package-lock.json dist/bluesky/package.json ${LAMBDA_TASK_ROOT}/
COPY dist/bluesky/lambda.js ${LAMBDA_TASK_ROOT}

RUN npm i --include prod

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda.handler" ]
