const seenBirds = [
  "American Robin",
  "Black-capped Chickadee",
  "Chipping Sparrow",
  "Common Grackle",
  "American Goldfinch",
  "Eastern Phoebe",
  "House Finch",
  "Mourning Dove",
  "Northern Cardinal",
  "Northern Flicker",
  "Tufted Titmouse",
  "White-breasted Nuthatch",
  "Downy Woodpecker",
  "House Sparrow",
  "Red-Winged Blackbird",
  "Red-bellied Woodpecker",
  "Hairy Woodpecker",
  "Blue Jay",
  "Baltimore Oriole",
  "Common Raven",
  "Bald Eagle",
  "Cooper’s Hawk",
  "American Crow",
  "Fish Crow",
  "Wild Turkey",
  "Pine Siskin",
  "Ruby-throated Hummingbird",
  "European Starling",
  "Gray Catbird",
  "Northern Mockingbird",
  "Orchard Oriole",
  "Evening Grossbeak",
  "Red-tailed Hawk",
  "Osprey",
  "Song Sparrow",
  "Chimney Swift",
  "Merlin",
  "Ruby-crowned Kinglet",
  "Rose-breasted Grosbeak",
  "Carolina Wren",
  "Eastern Towhee",
  "Cedar Waxwing",
  "Barred Owl",
  "Tree Swallow",
  "Barn Swallow",
  "Blue-gray Gnatcatcher",
  "Red-shouldered Hawk",
  "American Redstart",
  "Black-throated Green Warbler",
  "Dark-eyed Junco",
  "Savannah Sparrow",
  "Hermit Thrush",
  "Eastern Bluebird",
  "White-throated Sparrow",
  "Purple Finch",
  "Sharp-shinned Hawk",
  "Golden-crowned Kinglet",
];

export { seenBirds };
